const header22 = [
  { prop: 'zd1', label: '污染物', type: 'input', width: 120 },
  { prop: 'zd2', label: '污染物含量(μg)', type: 'input', width: 90 },
  { prop: 'zd3', label: '污染物浓度', type: 'input', width: 90 }
]
const temp22VOC = [
  { name: '苯' },
  { name: '乙二醇乙醚' },
  { name: '乙二醇甲醚' },
  { name: '乙酸异丁酯' },
  { name: '乙酸丁酯' },
  { name: '乙酸乙酯' },
  { name: '甲基异丁基酮' },
  { name: '环己酮' },
  { name: '丙酮' },
  { name: '丁酮' },
  { name: '异丁醇' },
  { name: '正丁醇' },
  { name: '苯乙烯' },
  { name: '乙苯' },
  { name: '偏-三甲苯' },
  { name: '均-三甲苯' },
  { name: '连-三甲苯' },
  { name: '邻-二甲苯' },
  { name: '间-二甲苯' },
  { name: '对-二甲苯' },
  { name: '甲苯' },
  { name: '异丙苯' },
  { name: '乙酸' }
]
const temp22VOCHJ644 = [
  { name: '1,1-二氯乙烯' },
  { name: '1,1,2-三氯-1,2,2-三氟乙烷' },
  { name: '氯丙烯' },
  { name: '二氯甲烷' },
  { name: '1,1-二氯乙烷' },
  { name: '順式-1,2-二氯乙烯' },
  { name: '三氯甲烷' },
  { name: '1,1,1-三氯乙烷' },
  { name: '四氯化碳' },
  { name: '1,2-二氯乙烷' },
  { name: '苯' },
  { name: '三氯乙烯' },
  { name: '1,2-二氯丙烷' },
  { name: '順式-1,3-二氯丙烯' },
  { name: '甲苯' },
  { name: '反式-1,3-二氯丙烯' },
  { name: '1,1,2-三氯乙烷' },
  { name: '四氯乙烯' },
  { name: '1,2-二溴乙烷' },
  { name: '氯苯' },
  { name: '乙苯' },
  { name: '间，对-二甲苯' },
  { name: '邻-二甲苯' },
  { name: '苯乙烯' },
  { name: '1,1,2,2-四氯乙烷' },
  { name: '4-乙基甲烷' },
  { name: '1,3,5-三甲基苯' },
  { name: '1,2,4-三甲基苯' },
  { name: '1,3-二氯苯' },
  { name: '1,4-二氯苯' },
  { name: '苄基氯' },
  { name: '1,2-二氯苯' },
  { name: '1,2,4-三氯苯' },
  { name: '六氯丁二烯' }
]
const temp22VOCHJ734 = [
  { name: '丙酮' },
  { name: '异丙醇' },
  { name: '正己烷' },
  { name: '乙酸乙酯' },
  { name: '苯' },
  { name: '六甲基二硅氧烷' },
  { name: '3-戊酮' },
  { name: '正庚烷' },
  { name: '甲苯' },
  { name: '环戊酮' },
  { name: '乳酸乙酯' },
  { name: '乙酸丁酯' },
  { name: '丙二醇单甲醚乙酸酯' },
  { name: '乙苯' },
  { name: '对/间二甲苯' },
  { name: '2-庚酮' },
  { name: '苯乙烯' },
  { name: '邻二甲苯' },
  { name: '苯甲醚' },
  { name: '苯甲醛' },
  { name: '1-癸烯' },
  { name: '2-壬酮' },
  { name: '1-十二烯' }
]
const header49 = [
  { prop: 'zd1', label: '污染物', type: 'input', width: 120 },
  { prop: 'zd2', label: '含量μg', type: 'input', width: 90 },
  { prop: 'zd3', label: '实测浓度mg/m3', type: 'input', width: 90 },
  { prop: 'zd4', label: '排放浓度mg/m3', type: 'input', width: 90 },
  { prop: 'zd5', label: '排放量kg/h', type: 'input', width: 90 }
]
const temp49VOC = [
  { name: '苯' },
  { name: '乙二醇乙醚' },
  { name: '乙二醇甲醚' },
  { name: '乙酸异丁酯' },
  { name: '乙酸丁酯' },
  { name: '乙酸乙酯' },
  { name: '甲基异丁基酮' },
  { name: '环己酮' },
  { name: '丙酮' },
  { name: '丁酮' },
  { name: '异丁醇' },
  { name: '正丁醇' },
  { name: '苯乙烯' },
  { name: '乙苯' },
  { name: '偏-三甲苯' },
  { name: '均-三甲苯' },
  { name: '连-三甲苯' },
  { name: '邻-二甲苯' },
  { name: '间-二甲苯' },
  { name: '对-二甲苯' },
  { name: '甲苯' },
  { name: '异丙苯' },
  { name: '乙酸' }
]
const temp49VOCHJ734 = [
  { name: '丙酮' },
  { name: '异丙醇' },
  { name: '正己烷' },
  { name: '乙酸乙酯' },
  { name: '苯' },
  { name: '六甲基二硅氧烷' },
  { name: '3-戊酮' },
  { name: '正庚烷' },
  { name: '甲苯' },
  { name: '环戊酮' },
  { name: '乳酸乙酯' },
  { name: '乙酸丁酯' },
  { name: '丙二醇单甲醚乙酸酯' },
  { name: '乙苯' },
  { name: '对/间二甲苯' },
  { name: '2-庚酮' },
  { name: '苯乙烯' },
  { name: '邻二甲苯' },
  { name: '苯甲醚' },
  { name: '苯甲醛' },
  { name: '1-癸烯' },
  { name: '2-壬酮' },
  { name: '1-十二烯' }
]

export {
  header22,
  temp22VOC,
  temp22VOCHJ644,
  temp22VOCHJ734,
  header49,
  temp49VOC,
  temp49VOCHJ734
}
